# Generated by Django 4.0.6 on 2022-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0002_member_email_member_first_name_member_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='know_god',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
