# Generated by Django 4.0.6 on 2022-07-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0005_know_remove_member_attend_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='know',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
    ]
