# Generated by Django 4.0.6 on 2022-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_know_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CONNECT TO COMMUNITY', max_length=250)),
                ('complete_a_connect_card', models.BooleanField()),
                ('attend_life_group', models.BooleanField()),
                ('attend_community_gathering', models.BooleanField()),
                ('attend_a_mens_or_womens_event', models.BooleanField()),
                ('participate_in_an_Age_Graded_Ministry', models.BooleanField()),
                ('join_our_mailing_list_or_notification_list', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='know',
            name='title',
            field=models.CharField(default='KNOW GOD', max_length=250),
        ),
    ]
