# Generated by Django 4.0.6 on 2022-07-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_connect_alter_know_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
    ]
