# Generated by Django 4.0.6 on 2022-07-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_connect_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GROW SPIRITUALLY', max_length=250)),
                ('read_the_Bible', models.BooleanField()),
                ('engage_in_Gods_word_through_journaling', models.BooleanField()),
                ('memorize_scripture', models.BooleanField()),
                ('join_a_D_group', models.BooleanField()),
                ('lead_a_d_group', models.BooleanField()),
                ('attend_a_mid_week_study', models.BooleanField()),
                ('fast_and_pray', models.BooleanField()),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='steps.member')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CHANGE THE WORLD', max_length=250)),
                ('invite_someone_to_church', models.BooleanField()),
                ('bring_a_guest_to_church', models.BooleanField()),
                ('have_a_gospel_conversation', models.BooleanField()),
                ('join_a_serving_team', models.BooleanField()),
                ('give_for_the_first_time', models.BooleanField()),
                ('become_a_repeat_giver', models.BooleanField()),
                ('become_a_regular_giver', models.BooleanField()),
                ('go_on_a_mission_trip', models.BooleanField()),
                ('lead_a_neighborhood_mission_project', models.BooleanField()),
                ('take_a_spiritual_gifts_inventory', models.BooleanField()),
                ('share_church_content_on_social_media', models.BooleanField()),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='steps.member')),
            ],
        ),
    ]
