# Generated by Django 4.0.6 on 2022-07-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0009_grow_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
        migrations.AlterField(
            model_name='grow',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
        migrations.AlterField(
            model_name='know',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steps.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
    ]
